### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by MarjoleinAardewijn** [GloryDaysApp/glorydays#156]

**Comment by GloryDaysApp** [comment]
@all-contributors please add <username> for <contributions>

**Comment by GloryDaysApp** [comment]
@all-contributors please add MarjoleinAardewijn, marissaverdonck, Zeijls, jenniferslagt, Coenmathijssen for code

**Comment by GloryDaysApp** [comment]
@all-contributors please add MarjoleinAardewijn for code

**Comment by GloryDaysApp** [comment]
@all-contributors please add marissaverdonck for code
@all-contributors please add marissaverdonck for code
@all-contributors please add Zeijls for code
@all-contributors please add Coenmathijssen for code

**Comment by GloryDaysApp** [comment]
@all-contributors please add @Coenmathijssen for code, bug, a11y, content, data, doc, design, ideas, maintenance, question and test

**Comment by GloryDaysApp** [comment]
@all-contributors please add @MarjoleinAardewijn for infra, bug, a11y, content, data, doc, design, ideas, maintenance, question, tutorial and test

**Comment by GloryDaysApp** [comment]
@all-contributors please add @marissaverdonck for code, bug, a11y, content, doc, design, ideas, maintenance, question and test

**Comment by GloryDaysApp** [comment]
@all-contributors please add @Zeijls for code, bug, a11y, content, doc, design, ideas, maintenance, question and test

**Comment by GloryDaysApp** [comment]
@all-contributors please add @jenniferslagt for code, bug, a11y, content, doc, design, ideas, maintenance, question and test

**Comment by GloryDaysApp** [comment]
@all-contributors please add @Coenmathijssen for data

**Comment by GloryDaysApp** [comment]
@all-contributors please add @Coenmathijssen for data
